/*
***********************************************************************************************************
* Program Name      : CCCToolsVSDirectMailPrefWrapper
* Description       : Wrapper class to store response
* Version           : 1.1
* Modification Log  : 26-05-2021
*----------------------------------------------------------------------------------------------------------
* RequirementId     JiraId      Version     Developer           Date            Description
*----------------------------------------------------------------------------------------------------------
* REQ_01            DP-37152    1.1         Ravikant Kedia      17-05-2021      Created Wrapper to store response.
* REQ_02            DP-37152    1.2         Ravikant Kedia      26-05-2021      code commenting.
***********************************************************************************************************
*/
public class CCCToolsVSDirectMailPrefWrapper {
    public String firstName;
	public String lastName;
	public String countryCode;
	public String streetAddress1;
	public String city;
	public String region;
	public String postalCode;
}