/*
 ***********************************************************************************************************
 * Program Name      : CCCToolsVSEmailPrefWrapper
 * Description       : Wrapper class to store the response.
 * Version           : 1.1
 * Modification Log  : 26-05-2021
 *----------------------------------------------------------------------------------------------------------
 * RequirementId     JiraId      Version     Developer           Date            Description
 *----------------------------------------------------------------------------------------------------------
 * REQ_01            DP-37150    1.1         Ravikant Kedia      17-05-2021      Created Wrapper class to store response.
 * REQ_02            DP-37150    1.2         Ravikant Kedia      26-05-2021      code commenting.
 ***********************************************************************************************************
 */
public class CCCToolsVSEmailPrefWrapper {
  public String fq;
  public String fq_change_date;
  public String result;
  public String cid;
}