public class RestApiConstants {
    public final static String GET_METHOD = 'GET';
    public final static String POST_METHOD = 'POST';
    public final static String AUTH_HEADER_KEY = 'Authorization';
    public final static String AUTH_SECRET_KEY = 'client_secret=';
    public final static String AUTH_ID_KEY = '&client_id=';
    public final static String GRANT_KEY = '&grant_type=';
    public final static String ACCESS_TOKEN = 'access_token';   
    public final static String CONTENT_TYPE = 'Content-Type';   

}