@IsTest
public class VSCCS_CarouselOrderDetailsTest {
    @IsTest
    static void testGetOrderDetails() {
        // Start test
        Test.startTest();
        vsccs_CarouselOrderDetails.Carousel carousel = new vsccs_CarouselOrderDetails.Carousel();
        vsccs_CarouselOrderDetails.Carousel frenchCarousel = new vsccs_CarouselOrderDetails.Carousel('fr');
        // Stop test
        Test.stopTest();

        // Assertions
        
    }
}